version: "3"
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    container_name: zookeeper
    user: root
    ports:
      - "10002:2181"
      - "10003:2182"
    environment:
      # 匿名登录--必须开启
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper:/bitnami/zookeeper

  kafka:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka_01
    restart: always
    user: root
    ports:
      - "10004:9092"
      - "9999:9999"
    volumes:
      - ./kafka:/bitnami/kafka"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka_01:9092  # kafka tcp 偵聽的ip
      # 客户端访问地址，更换成自己的，如果在虚拟机中，就填虚拟机 IP
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.2.110:10004  # kafka broker偵聽的ip
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # 允许使用PLAINTEXT协议(镜像中默认为关闭,需要手动开启)
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 关闭自动创建 topic 功能
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      # 全局消息过期时间 6 小时(测试时可以设置短一点)
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
      # 启用远程JMX 监控面板用
      - JMX_PORT=9999
    depends_on:
      - zookeeper

  # kafka叢集管理面板
  kafka_manager:
    image: 'hlebalbau/kafka-manager:latest'
    container_name: kafka_manager
    restart: always
    ports:
      - "10005:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: 123456
    depends_on:
      - zookeeper
      - kafka